### ISSUE TITLE
session的下载不支持断点续传

### ISSUE THREAD

**Issue by donggelaile** [netyouli/WHCNetWorkKit#11]
session的下载会有自己的缓存路径，不在你设置的那个路径，所以使用session下载每次查找resumeData都会返回空。就会重新下载。

**Comment by netyouli** [comment]
我知道，我并没有干扰session获取缓存的resumeData

**Comment by donggelaile** [comment]
那如何使用后台下载还能支持断点续传呢。。

**Comment by netyouli** [comment]
A download can be resumed only if the following conditions are met:

The resource has not changed since you first requested it

The task is an HTTP or HTTPS GET request

The server provides either the ETag or Last-Modified header (or both) in its response

The server supports byte-range requests

The temporary file hasn’t been deleted by the system in response to disk space pressure

**Comment by donggelaile** [comment]
好吧，感谢回答。我在看看。
